bg = "#282a36"
fg = "#f8f8f2"
tab_bar_bg = "#21222c"
tab_active_bg = "#6272a4"
tab_active_fg = "white"
tab_inactive_fg = "#6272a4"
prompt_bg = "#6272a4"
prompt_fg = "white"
status_bg = "#44475a"
status_fg = "white"
selection_bg = "#44475a"
line_nr_fg = "#6272a4"