bg = "#282828"
fg = "#ebdbb2"
tab_bar_bg = "#1d2021"
tab_active_bg = "#d79921"
tab_active_fg = "black"
tab_inactive_fg = "#928374"
prompt_bg = "#d79921"
prompt_fg = "black"
status_bg = "#504945"
status_fg = "white"
selection_bg = "#665c54"
line_nr_fg = "#928374"