bg = "#fafafa"
fg = "#1e1e1e"
tab_bar_bg = "#e6e6e6"
tab_active_bg = "#2965cc"
tab_active_fg = "white"
tab_inactive_fg = "#646464"
prompt_bg = "#2965cc"
prompt_fg = "white"
status_bg = "#c8c8c8"
status_fg = "black"
selection_bg = "#d2e6ff"
line_nr_fg = "#969696"