bg = "#272822"
fg = "#f8f8f2"
tab_bar_bg = "#1e1f1c"
tab_active_bg = "#66d9ef"
tab_active_fg = "black"
tab_inactive_fg = "#75715e"
prompt_bg = "#66d9ef"
prompt_fg = "black"
status_bg = "#75715e"
status_fg = "white"
selection_bg = "#49483e"
line_nr_fg = "#75715e"