bg = "#2e3440"
fg = "#d8dee9"
tab_bar_bg = "#3b4252"
tab_active_bg = "#88c0d0"
tab_active_fg = "black"
tab_inactive_fg = "#4c566a"
prompt_bg = "#88c0d0"
prompt_fg = "black"
status_bg = "#434c5e"
status_fg = "white"
selection_bg = "#434c5e"
line_nr_fg = "#4c566a"