bg = "#1b2b34"
fg = "#d8dee9"
tab_bar_bg = "#16242c"
tab_active_bg = "#6699cc"
tab_active_fg = "white"
tab_inactive_fg = "#65737e"
prompt_bg = "#6699cc"
prompt_fg = "white"
status_bg = "#65737e"
status_fg = "white"
selection_bg = "#4f5b66"
line_nr_fg = "#65737e"