bg = "#002b36"
fg = "#839496"
tab_bar_bg = "#073642"
tab_active_bg = "#268bd2"
tab_active_fg = "white"
tab_inactive_fg = "#586e75"
prompt_bg = "#268bd2"
prompt_fg = "white"
status_bg = "#073642"
status_fg = "white"
selection_bg = "#073642"
line_nr_fg = "#586e75"