; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Zap Nano"
#define MyAppVersion "0.1.0"
#define MyAppPublisher "Zap Editor team"
#define MyAppExeName "zapnano.exe"
#define MyAlternativeExeName "znano.exe"

[Setup]
AppId={{5E22B0DF-ECB3-4A2D-AEE5-827D8C5B6F9A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\Programs\ZapNano
PrivilegesRequired=lowest
DisableProgramGroupPage=yes
DisableDirPage=no
UsePreviousAppDir=no
OutputBaseFilename=zapnano_setup
OutputDir=.
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64
ChangesEnvironment=yes
SetupIconFile=resources\images\ZapNano.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "..\target\release\zapnano.exe"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "bin\znano.cmd"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs

[Registry]
Root: HKCU; Subkey: "Environment"; ValueType: expandsz; ValueName: "Path"; ValueData: "{olddata};{app}\bin"; Check: NeedsAddPath; Flags: preservestringtype

[Code]
function SendMessageTimeout(hWnd: HWND; Msg: UINT; wParam: Longint; lParam: String; fuFlags: UINT; uTimeout: UINT; var lpdwResult: DWORD): Longint;
  external 'SendMessageTimeoutW@user32.dll stdcall';

function NeedsAddPath(): Boolean;
var
  OldPath: String;
  NewPath: String;
begin
  if RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', OldPath) then
  begin
    NewPath := ExpandConstant('{app}\bin');
    Result := Pos(Uppercase(NewPath), Uppercase(OldPath)) = 0;
  end
  else
  begin
    Result := True;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultAddr: DWORD;
begin
  if CurStep = ssPostInstall then
  begin
    SendMessageTimeout(
      HWND_BROADCAST,
      $001A, // WM_SETTINGCHANGE
      0,
      'Environment',
      $0002, // SMTO_ABORTIFHUNG
      5000,
      ResultAddr
    );
  end;
end;

procedure RemovePath(appDir: string);
var
  Path: String;
  AppBin: String;
begin
  AppBin := appDir + '\bin';
  if RegQueryStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', Path) then
  begin
    StringChangeEx(Path, ';' + AppBin, '', True);
    StringChangeEx(Path, AppBin + ';', '', True);
    StringChangeEx(Path, AppBin, '', True);
    RegWriteExpandStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', Path);
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultAddr: DWORD;
begin
  if CurUninstallStep = usUninstall then
  begin
    RemovePath(ExpandConstant('{app}'));
    SendMessageTimeout(HWND_BROADCAST, $001A, 0, 'Environment', $0002, 5000, ResultAddr);
  end;
end;
